import "./styles/index.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "News parser",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="app">{children}</body>
    </html>
  );
}
